# This file is automatically generated. Please do not modify.

from . import AsciiArt

arch_small = AsciiArt(match=r'''"arch_small"''', color='6 7 1', ascii=r"""
   _____ ______ ______ _____ 
  / ____|  ____|  ____/ ____|
 | |  __| |__  | |__ | |  __ 
 | | |_ |  __| |  __|| | |_ |
 | |__| | |____| |___| |__| |
  \_____|______|______\_____|
""")
    
