# AUTOMATICALLY GENERATED by `shtab`



complete hyfetch \
        'c/--/(mode test-distro preset config c-scale c-set-l config-file ascii-file version debug distro help backend)/' \
        'c/-/(m h V C p b c -)/' \
        'n/-p/(american india)/' \
        'n/--preset/(american india)/' \
        'n/-m/(8bit rgb)/' \
        'n/--mode/(8bit rgb)/' \
        'n/-b/(neofetch fastfetch fastfetch-old)/' \
        'n/--backend/(neofetch fastfetch fastfetch-old)/' \
        'p/*/()/'
